### ISSUE TITLE
[3장] 함수가 아닌 코루틴을 중단시킨다

### ISSUE THREAD

**Issue by wotosts** [FroblemSolver/books#1]
3장. 33p

코루틴의 중단이라는 개념이 말 그대로 코루틴을 중단시킨다 라는 것인데
실제로 책의 내용을 읽다 보니 헷갈리네요. 

**중단 함수는 코루틴이 아니고, 단지 코루틴을 중단할 수 있는 함수라 할 수 있습니다.**  << 요 부분이
제가 이해한 바로
중단 함수는 코루틴 또는 중단 함수 내에서만 호출이 가능하다 -> 즉, 코루틴 내에서 중단 함수가 동작하고 있다.
는 것인데 코루틴을 중단하면 함수 동작도 진행이 되지 않는게 맞지 않나요?

---

처음에 의견 나눴던 것처럼, 질문의 질에 대해 고민하고 올려야 하긴 하는데
이건 정말 헷갈려서요

**Comment by bossm0n5t3r** [comment]
> 코루틴을 중단하면 함수 동작도 진행이 되지 않는게 맞지 않나요?

여기서 말하는 "함수 동작"이 "코루틴을 호출한 함수"의 동작을 말씀하시는건가요?

**Comment by wotosts** [comment]
> > 코루틴을 중단하면 함수 동작도 진행이 되지 않는게 맞지 않나요?
> 
> 여기서 말하는 "함수 동작"이 "코루틴을 호출한 함수"의 동작을 말씀하시는건가요?

맞습니당,

**Comment by JaewonKim04** [comment]
첫번째 예시(33p)에서 말하는 코루틴 : main(), suspendAndSetContinuation()
함수가 아니라는건 suspendAndSetContinuation()만 중단하는게 아닌 main() 까지도 중단하는것이기 때문에 resume()이 호출되지 않음

두번째 예시(33~34p)의 예시를 보면 main() 안에 launch{}를 통해 새로운 코루틴을 만들었기 때문에 suspendAndSetContinuation() 를 호출해도 launch{} 안의 코루틴은 중단되지 않음 -> 1초후에 코루틴 resume을 호출하는 코드가 실행 되기 때문에 After 이 출력됨
