### ISSUE TITLE
[기타] 값이 들어왔음을 알려주는 방식?

### ISSUE THREAD

**Issue by wotosts** [FroblemSolver/books#2]
코루틴을 통해 io 작업을 호출하면 값이 들어오기까지 코루틴이 중단되고, 값이 들어오면 코루틴이 재개되는데요. 
값이 들어왔음을 알려주는 작업은 어떤 방식으로 진행되는걸까요?
네트워크 라이브러리 등 외부 라이브러리가 하는 작업이겠지만 궁금하네요.

io 작업에서 값이 들어온 것을 지속적으로 확인하는 역할을 담당하는 것이 있을 텐데,
이 것도 스레드를 잡고 있을거라고 예상되거든요.

**Comment by JaewonKim04** [comment]
OKHttp 액션과 관련된 내용이었음 -> 찾아보니 스레드를 잡고 response가 올 때 까지 계속 확인하고있었음.

**Comment by wotosts** [comment]
예시로 retrofit을 들어보자면,retrofit.enqueue 호출 시 okhttp.enqueue를 호출하고
okhttp는 이런 콜들을 별도 워커 스레드에서 동작하게끔 runnable로 구현해서 사용하고 있다. (덤으로 dispatcher.io 를 사용할 필요가 없는 이유)
즉, 응답이 왔다는 것에 대한 확인은 다른 스레드가 담당하며, 해당 스레드에서 continuation.resumeWith을 호출하여 재개되는 것.
